application: multiuserblog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: multiuserblog.app
- url: /css
  static_dir: css

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
