application: multiuserblog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates/css
  static_dir: templates/css

- url: .*
  script: multiuserblog.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
